server.port: 8089

mybatis-plus:
  #mybatis
  #Mapper路径
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/com/seawaterbt/ssm/module/*/dao/mapping/*.xml

  #实体,枚举类扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.zj.springboot.demomybatisplus.model
  #  type-enums-package: com.zj.springboot.demomybatisplus.entity.enums

  global-config:
    db-config:
      #      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      #      id-type: id_worker
      #      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      #      field-strategy: not_empty
      #      #驼峰下划线转换
      #      column-underline: true
      #      #数据库大写下划线转换
      #      #capital-mode: true
      #      #逻辑删除配置
      #      logic-delete-value: Y
      #      logic-not-delete-value: N
      #数据库类型。支持主流的数据库
      db-type: sqlserver
    #刷新mapper 调试神器
    refresh: true
      #    sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
      #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    #数据库字段与数据对象字段的映射策略
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
spring:
  profiles:
    active: dev
debug: false