#spring
spring:
  #mysql
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/poker_admin?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    url: jdbc:sqlserver://localhost:1433;DatabaseName=poker_admin
#    username: root
    username: SA
    password: Qwe!@#123
#    password:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #  devtools:
    #      restart:
    #        enabled: true     #这里是为了热部署的，与mybatis是无关的
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=false;druid.stat.slowSqlMillis=500

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
logging:
  config: classpath:logback-spring.xml